export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const ADD_CONVERSATION = 'ADD_CONVERSATION'
export const SET_LOADING_CONVERSATIONS = 'SET_LOADING_CONVERSATIONS'
export const CONVERSATIONS_FAILURE = 'CONVERSATIONS_FAILURE'
