export const GET_USERS = 'GET_USERS'
export const ADD_USER = 'ADD_USER'
export const SET_LOADING_USERS = "SET_LOADING_USERS"
export const USERS_FAILURE = "USERS_FAILURE"
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const SET_LOADING_USER_PROFILE = "SET_LOADING_USER_PROFILE"
export const GET_USER_PROFILE_POSTS = 'GET_USER_PROFILE_POSTS'
export const SET_LOADING_USER_POSTS = "SET_LOADING_USER_POSTS"