export const SET_ACTIVE_USER = "SET_ACTIVE_USER"
export const SET_LOADING_ACTIVE_USER = 'SET_LOADING_ACTIVE_USER'
export const ACTIVE_USER_FAILURE = 'ACTIVE_USER_FAILURE'
export const CHECK_ACTIVE_USER = 'CHECK_ACTIVE_USER'
export const SET_LOADING_CHECK = 'SET_LOADING_CHECK'